;This SCM1 entry is for PS Control Actor Framework
[scm1_normal]
ModeName=SCM1Normal
VISAAddress=TCPIP::192.168.2.3::7180::SOCKET
StaffOnly=0
Breakpoints="110"
Rates="4.0"
HasPSwitch=True
SwitchHtrCurrent=60.000000
SwitchWaitTime=60.000000
FieldCurrentRatio=0.165620
StabilitySetting=0.0
MaxCurrent=108.690000
QuenchDetectEnable=True
[scm1_lambda]
ModeName=SCM1Lambda
VISAAddress=TCPIP::192.168.2.3::7180::SOCKET
StaffOnly=1
Breakpoints="121"
Rates="1.5"
HasPSwitch=True
SwitchHtrCurrent=60.000000
SwitchWaitTime=60.000000
FieldCurrentRatio=0.165620
StabilitySetting=0.0
MaxCurrent=120.76
QuenchDetectEnable=True
[scm1_train]
ModeName=SCM1Train
VISAAddress=TCPIP::192.168.2.3::7180::SOCKET
StaffOnly=1
Breakpoints="80,100,108.68,120.76"
Rates="4.0,2.0,0.75,0.75"
HasPSwitch=True
SwitchHtrCurrent=60.000000
SwitchWaitTime=60.000000
FieldCurrentRatio=0.165620
StabilitySetting=0.0
MaxCurrent=108.69
QuenchDetectEnable=True
[scm1resistor]
ModeName=ResistorTest
VISAAddress=TCPIP::192.168.2.3::7180::SOCKET
StaffOnly=1
Breakpoints="110"
Rates="100.0"
HasPSwitch=True
SwitchHtrCurrent=60.000000
SwitchWaitTime=5.000000
FieldCurrentRatio=1.0
StabilitySetting=100.0
MaxCurrent=5.0
QuenchDetectEnable=False
